{
 "title": "Gitlab-KPI",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Project_key",
    "label": "Project_key",
    "query": "from(bucket: \"gitlab_test\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"project\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Repository size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gitlab_test\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"statistics\")\n  |> filter(fn: (r) => r[\"project_id\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"repository_size\")"
    }
   ]
  },
  {
   "title": "Issue total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gitlab_test\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"issue_total\")\n  |> filter(fn: (r) => r[\"project_id\"] == \"${Project_key}\")\n"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -7d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"issue_id\")\n  |> unique(column: \"issue_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 7d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"7 days ago\": r._value}) )"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -10d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"issue_id\")\n  |> unique(column: \"issue_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 10d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"10 days ago\": r._value}) )"
    }
   ]
  },
  {
   "title": "Commit total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"gitlab_test\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"commit_total\")\n  |> filter(fn: (r) => r[\"project_id\"] == \"${Project_key}\")\n"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -7d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"commit_id\")\n  |> unique(column: \"commit_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 7d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"7 days ago\": r._value}) )"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -10d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"commit_id\")\n  |> unique(column: \"commit_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 10d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"10 days ago\": r._value}) )"
    }
   ]
  },
  {
   "title": "Merge Request total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"gitlab_test\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mrs_total\")\n  |> filter(fn: (r) => r[\"project_id\"] == \"${Project_key}\")\n"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -7d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mrs_id\")\n  |> unique(column: \"mrs_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 7d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"7 days ago\": r._value}) )"
    },
    {
     "query": "import \"date\"\nfrom(bucket: \"gitlab\")\n  |> range(start: -10d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mrs_id\")\n  |> unique(column: \"mrs_id\")\n  |> map(fn:(r) => ({r with \"created_at\": time(v: r[\"created_at\"])}))\n  |> filter(fn: (r) => r[\"created_at\"] < date.sub(d: 10d, from: now()))\n  |> group()  \n  |> count()\n  |> map(fn: (r) => ({ \"10 days ago\": r._value}) )"
    }
   ]
  }
 ]
}